[build]
dockerfilePath = "webapp/Dockerfile.prod"
dockerContextDir = "webapp"

[deploy]
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
